### User create
POST http://localhost:3000/users
Content-type: application/json

{
  "user_name": "Katrina",
  "email": "katrina@email.com",
  "password": "password",
  "password_conformation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "ben@email.com",
  "password": "password"
}