@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzA1MzU2ODF9.ND8DdL0yyQ3A8xoun02fHzwI_PL0tyDevuvloLZJoNA

### User create
POST http://localhost:3000/users
Content-type: application/json

{
  "user_name": "Katrina",
  "email": "katrina@email.com",
  "password": "password",
  "password_conformation": "password"
}

### User show
GET http://localhost:3000/users/1
Authorization: Bearer {{jwt}}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "ben@email.com",
  "password": "password"
}

### Show user friendships
GET http://localhost:3000/users/1/friendships

### Create new friendship
POST http://localhost:3000/users/1/friendships
Content-type: application/json
Authorization: Bearer {{jwt}}

{
  "friend_id": 4
}


### Create bet
POST http://localhost:3000/users/1/bets
Content-type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "Basketball",
  "description": "First to 21",
  "wager_item": "Punch to the thigh",
  "wager_amount": 4,
  "friend_id": 2
}